### ISSUE TITLE
errors 

### ISSUE THREAD

**Issue by hhz0328** [Roboprotos/maxon_epos4_ros1#1]
I face some errors and don't know how to solve it :
**[ERROR] [1684030458.733188550]: Received error frame: 20000004#0000000000005f00
[ERROR] [1684030458.756318871]: abort1a01#2, reason: Object cannot be mapped to the PDO.
[ERROR] [1684030458.756341994]: Could not process message**
[ INFO] [1684030458.756593035]: Current state: 2 device error: system:125 internal_error: 0 (OK)
[ INFO] [1684030458.756697209]: Current state: 0 device error: system:125 internal_error: 0 (OK)
[ INFO] [1684030458.756708087]: Current state: 0 device error: system:0 internal_error: 0 (OK)
[ INFO] [1684030458.756760827]: Current state: 0 device error: system:0 internal_error: 0 (OK)
**[ERROR] [1684030458.757075233]: Initializing failed: /tmp/binarydeb/ros-noetic-canopen-master-0.8.5/src/sdo.cpp(429): Throw in function void canopen::SDOClient::transmitAndWait(const canopen::ObjectDict::Entry&, const canopen::String&, canopen::String*)
Dynamic exception type: boost::wrapexcept<canopen::TimeoutException>
std::exception::what: SDO
[canopen::tag_objectdict_key*] = 1a01sub2**

**Comment by hhz0328** [comment]
I have solved it.The reason for the error is that the COB_ID does not match the NODE of the motor when configuring the motor parameters.

**Comment by Roboprotos** [comment]
Great, glad you found the solution. I close this issue.
