### ISSUE TITLE
CSP Mode

### ISSUE THREAD

**Issue by hhz0328** [Roboprotos/maxon_epos4_ros1#2]
I would now like to try out the csp mode. But I only have one maxon motor,  but the sample contains two motor joints,how should I go about it？

**Comment by Roboprotos** [comment]
Hi, you could try to duplicate all files which names end with "2dof_csp" and rename as "1dof_csp" in config, launch and urdf folder. You can then remove all the occurrences of the second joint, link, transmission etc in those files. To use moveit you will also have to modify all the files which mention this second axis accordingly and change the xacro file name in planning_context.launch to the file name you've set previously with "1dof_csp".

Let me know if that works and feel free to send a PR if you want to share your single motor CSP test.

**Comment by hhz0328** [comment]
Thanks for the answer, I managed to get the electric motor moving and reached pos 1.I am a third year university student and I want to implement a lower limb exoskeleton by self-learning with four motors in csp mode, which I think would be cool. Can you give me some learning advice on the code sample of the csp mode, I don't know how I should go about modifying it now, how to build the kinematic model of the four motors on the lower limb exoskeleton, and how to send different action commands with the same timing to the motors on the two leg sides. When finished, I would like to share my own case code, which would be valuable.

**Comment by Roboprotos** [comment]
Hi, you need to proceed step by step by adapting the code to 4 DOF in CSP mode and you can run again the MoveIt Setup Assistant to generate a proper moveit package for your robot. You'll be able to also add your CAD files to the URDF. 
I suggest you to ask specific questions on ROS Answers as you go on your project, tag them with ros_canopen and I'll probably see them (GitHub Issue is related to actual package issues).
Let me know if you can share your code, thanks !

**Comment by hhz0328** [comment]
Sorry，I had some problems with the operation when I uploaded the code. It was my first time on github, uploading branch code.
I loaded two files into the code section.
