### ISSUE TITLE
Initialization Failure with Maxon Motor Using IXXAT USB-to-CAN 

### ISSUE THREAD

**Issue by ika-si** [Roboprotos/maxon_epos4_ros1#5]
Hello, thanks for this useful software !

I am encountering an initialization failure when attempting to operate a Maxon motor using the IXXAT USB-to-CAN V2 interface.

**Environment:**
・Ubuntu20.04LTS
・IXXAT USB-to-CAN V2
・EPOS4 compact 50/5 can

**Steps to Reproduce:**
In the first terminal
$ roslaunch maxon_epos4_ros_canopen maxon_epos4_canopen_motor_1dof_ppm.launch
In the second terminal
$ rosservice call /maxon/driver/init

**Actual Behavior:**
The initialization process fails with the following error messages in the console:

[ INFO] [1707807331.767948279]: Using fixed control period: 0.010000000
[ INFO] [1707807335.028286513]: Initializing...
[ INFO] [1707807335.028768010]: Current state: 1 device error: system:0 internal_error: 0 (OK)
[ INFO] [1707807335.029171750]: Current state: 2 device error: system:0 internal_error: 0 (OK)
[ INFO] [1707807345.029996332]: Current state: 0 device error: system:0 internal_error: 0 (OK)
[ INFO] [1707807345.030132079]: Current state: 0 device error: system:0 internal_error: 0 (OK)
[ERROR] [1707807345.030785136]: Initializing failed: could not reset node '1'

I am seeking assistance in resolving this initialization failure. Any insights, suggestions, or solutions would be greatly appreciated.

**Comment by Roboprotos** [comment]
Have you been able to solve this issue ?

**Comment by ika-si** [comment]
I've successfully resolved the issue. It was due to the DIP switch settings on the EPOS4.
