### ISSUE TITLE
Code Sharing

### ISSUE THREAD

**Issue by hhz0328** [Roboprotos/maxon_epos4_ros1#6]
I managed to implement the exoskeleton robot drive based on your code.I'm willing to share my code.

https://github.com/hhz0328/ros1_canopen_maxon_control

**Comment by hhz0328** [comment]
I asked you a question last year, thanks for the answer.

https://github.com/Roboprotos/maxon_epos4_ros1/issues/2

**Comment by Roboprotos** [comment]
Thank you for sharing your code.
